### PR TITLE
Create task screen

### LINKED ISSUE #111: Need Task View Screen
The application does not allow users to click on a task and view it in a Task View Screen.
- This functionality is described in the [SRS](https://github.com/smacademic/project-cgkm/wiki/Software-Requirements-Specification) as **Req 2.3: Task View**
- This functionality is displayed in the [UI Design Template](https://github.com/smacademic/project-cgkm/wiki/ArcPlanner-UI-Design-Template)

### PR DESCRIPTION
**Pull request by jgrabowski121**
This PR address and closes #111 
- The Task Screen does not allow users to update, delete, or complete as mentioned in the [SRS](https://github.com/smacademic/project-cgkm/wiki/Software-Requirements-Specification), but this should be addressed in a seperate PR
- The `description` field is currently set to have a height of (.30 * screen height), but can be changed to expand with its text value if we decide that is the better option

### CODE REVIEW

**Comment by jgrabowski121** [comment]
@MatthewChastain, as you have the most experience in the screen navigation, please review the method I implemented in `task_tile.dart` and 'task_screen.dart' and give feedback on this implementation if you have the time.

**Comment by jgrabowski121** [comment]
Please wait to review. I have discovered a bug and I will update when it is resolved

**Comment by jgrabowski121** [comment]
The bug has been fixed

**Comment by KevinKelly25** [comment]
I am seeing the task but receiving the following errors:

<details><summary>Long Error Message</summary>
<p>

```
I/flutter ( 9967): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9967): The following NoSuchMethodError was thrown building StreamBuilder<Task>(dirty, state:
I/flutter ( 9967): _StreamBuilderBaseState<Task, AsyncSnapshot<Task>>#1549a):
I/flutter ( 9967): The getter 'title' was called on null.
I/flutter ( 9967): Receiver: null
I/flutter ( 9967): Tried calling: title
I/flutter ( 9967):
I/flutter ( 9967): When the exception was thrown, this was the stack:
I/flutter ( 9967): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 9967): #1      titleField (package:arcplanner/src/ui/task_screen.dart:76:18)
I/flutter ( 9967): #2      TaskScreen.build.<anonymous closure> (package:arcplanner/src/ui/task_screen.dart:41:17)
I/flutter ( 9967): #3      StreamBuilder.build (package:flutter/src/widgets/async.dart:423:74)
I/flutter ( 9967): #4      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
I/flutter ( 9967): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter ( 9967): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
I/flutter ( 9967): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 9967): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 9967): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #32     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
I/flutter ( 9967): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter ( 9967): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 9967): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #53     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 9967): #54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 9967): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 9967): #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #72     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 9967): #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 9967): #80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #98     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 9967): #99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #104    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #105    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #108    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 9967): #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #117    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 9967): #118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #120    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 9967): #121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #123    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 9967): #124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #126    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 9967): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #131    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #132    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 9967): #133    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #137    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #138    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #144    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #145    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 9967): #146    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #147    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #149    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 9967): #150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #153    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #154    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #158    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 9967): #159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #164    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 9967): #165    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #169    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #170    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #171    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #174    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 9967): #175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #178    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #179    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #180    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #181    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #182    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #184    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #185    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #186    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 9967): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #191    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 9967): #193    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 9967): #194    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter ( 9967): #195    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter ( 9967): #196    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter ( 9967): #197    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4659:32)
I/flutter ( 9967): #198    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 9967): #199    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9967): #200    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:508:16)
I/flutter ( 9967): #201    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9967): #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #203    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #204    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9967): #205    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9967): #206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #207    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #208    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9967): #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9967): #210    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9967): #211    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9967): #212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #213    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #214    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9967): #215    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9967): #216    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9967): #217    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9967): #218    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9967): #219    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9967): #220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9967): #221    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9967): #222    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter ( 9967): #223    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 9967): #224    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter ( 9967): #225    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 9967): #226    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter ( 9967): #227    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter ( 9967): #231    _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 9967): #232    _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter ( 9967): (elided 3 frames from package dart:async)
I/flutter ( 9967): ════════════════════════════════════════════════════════════════════════════════════════════════════

```
</p>
</details>

**Comment by jgrabowski121** [comment]
Thank you @KevinKelly25 for the feedback;
I found the issue was that the `StreamBuilder` in `task_screen.dart` needed the `initialData` parameter set so that it did not build the screen with a non-existent task as it gets the stream data. I believe my last commit fixed the issue

**Comment by jgrabowski121** [comment]
@jrm86, thank you for adding the arc deletion functionality. In my tests, the arc is successfully deleted but i noticed that it still appears in the arc view after deletion, this however I believe to be an unrelated issue with that actual deletion of the arc. 
Note: I discovered a bug in the arc view and I will be creating an issue for it, in short if an arc only has task children, the back button will go to the previous screen and not reload the arc view as it should

**Review by KevinKelly25 — APPROVED** [review]
It works well now. Thank you for fixing the issue

**Comment by MatthewChastain** [comment]
UI looks good, the only thing I notice is that pressing the back button doesn't take you to the screen you launched the task from, but rather takes you back to the base Arc View screen with the highest level of Arcs. Was this intentional?

**Comment by jgrabowski121** [comment]
@MatthewChastain , the current implementation returns the user to the calling screen. This will be either the arc view screen or the home screen depending on which the task was selected from. 

The reason the arc view screen displays the highest level of arcs is because the screen is being reloaded when the task screen is popped. I will try to work towards a fix for this and load the proper level of the arcs but I am unsure if this can be completed by WRD on May 9th or if it is a priority. I feel that for the time being we should either keep it how it is or have the back button return the user to the home screen unconditionally so we can ensure the screen is functional for the WRD demo

**Comment by jrm86** [comment]
Looks good👍. Will approve when merge conflict is resolved.

**Review by MatthewChastain — APPROVED** [review]
I think leaving as is for WRD is fine, thanks @jgrabowski121.

**Review by jrm86 — APPROVED** [review]

**Pull request merged**
