### PR TITLE
Add settings screen

### LINKED ISSUE #31: Need Settings Screen
ArcPlanner needs a Settings screen to facilitate changing notification, login, and other settings. Most of these settings will involve extensions but setting up this screen early on in development will allow for easily adding extensions later on. 

A visual template of the UI along with details for the screen can be found [here](https://github.com/smacademic/project-cgkm/wiki/ArcPlanner-UI-Design-Template#settings).

### PR DESCRIPTION
**Pull request by jgrabowski121**
This PR will add the settings screen to the repo and closes #31
In addition to adding the settings screen the following changes were made
- A `Settings` button was added to the about screen
- Changes were made to `main.dart` to allow the settings screen to be added

### CODE REVIEW

**Review by jrm86 — APPROVED** [review]
Tests out well, and the screens look great.  Thanks @jgrabowski121!

**Review by MatthewChastain — APPROVED** [review]
I believe this will cause a few merge conflicts with the addition of the Home screen and Side-Menu but the code here looks good and we will address the conflicts when we merge.

**Comment by jgrabowski121** [comment]
As mentioned by @MatthewChastain  in issue #50, this screen could be coded to use a ListTile embedded inside of a ListView instead a FlatButton thats is nested in a ListView builder (and additional child objects). ListTile is most likely the best option as it will allow for us to add additional setting buttons easily, and they will each be able to have different designs if necessary. Please reply with your thoughts on if this we agree that this change should be made, and if we should modify it in this PR or as a patch for the next Milestone M5.

**Comment by KevinKelly25** [comment]
If you think the changes can be made before our scrum/release I think you should try to make them. Otherwise I think we can merge this PR and patch it once the screen has usable info. If we go with the later it may be worth keeping issue #31 open

edit: changed issue number

**Comment by MatthewChastain** [comment]
I agree with @KevinKelly25 on this. If you have the time I'd say make the changes but if you don't have the time then it's not a pressing issue and we can make the changes in M5.

**Review by KevinKelly25 — APPROVED** [review]
Screen looks good, thank you @jgrabowski121

**Pull request merged**
