### PR TITLE
Add Calendar Screen UI

### PR DESCRIPTION
**Pull request by KevinKelly25**
This PR adds a calendar screen to the app. This PR is only for UI functionality and is not connected to the BLoC or Arcs/Task Objects at all.  

To add the calendar to the app I have imported the `table_calendar` package which requires the `intl` package in order to allow variation of calendar languages. While the variation of calendar languages is not needed now the ability to switch easily from this package will help a lot in the future when adding varying language options.

I have updated the drawer menu, so getting to the page is a simple as clicking on the calendar in the drawer. 

I am somewhat unsure about the coloring and format so I am very open to suggestions/comments about the styling. The package for the calendar is very flexible in terms of design.  

Much of the screen is taken and customized from the package example found [here](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart) as it matched what I was envisioning quite well and had a very good example "events" that will be replaced with Arcs/Tasks when the functionality is added. 

The package for the calendar is found [here](https://pub.dartlang.org/packages/table_calendar)

### CODE REVIEW

**Review by jrm86 — APPROVED** [review]
Really great work, and runs smoothly on my Pixel emulator.

I'm fine with the color scheme and formatting, though from the package's online documentation, it looks like it's fairly simple to make changes in the future if we decide to do so.

**Review by MatthewChastain — APPROVED** [review]
This looks great @KevinKelly25! I like the little number in the bottom right of day tiles that shows how many items are on that day. I think this works really well and looks good!

**Review by jgrabowski121 — APPROVED** [review]
Everything looks really good in my Nexus 6 emulator, thanks for working on this @KevinKelly25! I also think that the color scheme looks good and fits our overall theme, the only suggestion I have is we may want to have dividing lines between each row of days in a future update.

**Comment by jgrabowski121** [comment]
@KevinKelly25 the `intl` library is also being used by the `add_arc_screen` to format the date and it has some very nice formatting options

**Pull request merged**
