### PR TITLE
Add arc creation screen

### PR DESCRIPTION
**Pull request by jgrabowski121**
This PR adds the arc view screen to the project in the file `add_arc_screen.dart` .This screen will allow for users to enter a new arc, as per the issue #15. This PR only adds the UI and the ability to add arcs has not yet been implemented. 

Upon review, note that this screen:
- Will allow a user to select a parent `Arc` but this will need to be modified to allow the removal of the parent `Arc` once selected (if needed)
- Should display what `Arcs` are be a parent of the `Arc` selected (and that the selection is a sub arc) This is to conform with the `Location` field in the [UI design template](https://github.com/smacademic/project-cgkm/wiki/ArcPlanner-UI-Design-Template)
- Is not displayed as a splash screen over the screen called from because it can be called from the side menu bar
- Requires changes to the Arc class to conform to the [UI design template](https://github.com/smacademic/project-cgkm/wiki/ArcPlanner-UI-Design-Template), or the template should be modified: 
Location is in the UI design template but has been replaced with the parent field (can be changed back)
EndDate is in the UI design template and should be added to the `Arc` class

I have noted that the file may need to be renamed `create_arc_screen.dart` for clarity.

### CODE REVIEW

**Comment by MatthewChastain** [comment]
Thanks for the PR @jgrabowski121! 

Something that I see as I look at the changes is that a drop-down menu doesn't allow a user to see exactly where they will placing the Arc as it cannot show any sort of hierarchy. For this reason I don't believe a drop-down is the best choice for this aspect of the screen. 

I think this being its own screen instead of a pop-up dialog is fine and I like the addition of the top app bar.

**Comment by jgrabowski121** [comment]
Thank you for the feedback @MatthewChastain. I agree that the drop down menu should instead be a new screen, I will remove the drop down menu but for now the parent field will not be edit-able until a new screen i made for the functionality.

**Comment by jgrabowski121** [comment]
I have edited the file to replace the drop down menu with a raised button that will be used to go to a new screen that will allow users to select a parent arc as per the suggestion from @MatthewChastain

**Comment by KevinKelly25** [comment]
Thank you @jgrabowski121, it looks good. The only thing I noticed that is missing from the screen is the `dueDate` which I know you mentioned in the original post is missing. However, as of the completion of #69 it has been added to dev. I believe that field should be added to this screen for this PR now. 

I agree with @MatthewChastain that a separate screen is a good choice for selecting a parent.

**Comment by jgrabowski121** [comment]
@KevinKelly25 , I am unsure if i will have time to make the addition of dueDate with proper utilization of a validator and the necessary additions to the `bloc` class before our PR edit deadline of 10am tomorrow. I can however add the field to the screen and add the actual stream functionality during the next milestone.

**Comment by KevinKelly25** [comment]
That is fine. This is PR for UI more then the functionality anyway.

**Comment by jgrabowski121** [comment]
I have added the Due Date field. Additionally, I have replaced the Column wrapping the widgets with a ListView so that a user may scroll through the field widgets if they do not all fit when they open their keyboard instead of some fields being hidden by the keyboard when it opens. This can possibly be replaced by utilizing height constraints but I believe this is the better option.

**Review by KevinKelly25 — APPROVED** [review]
Looks ready to merge. Thank you

**Review by MatthewChastain — APPROVED** [review]
The use of a ListView was a good choice, allowing for better visibility of input on smaller devices. Tested and everything works as it should on the UI side, code looks good as well. Thanks for the work on this @jgrabowski121!

**Review by jrm86 — APPROVED** [review]
Just took a look with the latest changes. Looks really good. Thanks @jgrabowski121

**Pull request merged**
