### PR TITLE
Add server db create script

### LINKED ISSUE #8: Need SQL Create Table Script [Server DB]
Repo is missing a create script for the SQL database server that will be used for the future database server implementation.

Solution is to create a script to create the SQL db tables.
This should be based off of the following [wiki](https://github.com/smacademic/project-cgkm/wiki/Logical-Schema-and-Table-Summaries).

### PR DESCRIPTION
**Pull request by jgrabowski121**
Add a script `createServerTables` to create the db tables within a Postgres server
This file is for use in our future server implementation and is not intended to be used with SQL Lite
This PR closes #8

### CODE REVIEW

**Comment by KevinKelly25** [comment]
Thank you @jgrabowski121 for making this PR. I see a few issues:

- I do not believe we should be using `User` for the name of a table because it is a reserved word in PostgreSQL. I believe this will result in errors in most, if not all, versions of PostgreSQL. The alternate would be use something like `userData`. Alternatively, if we decided it is important we user User as a table name we need to surround it in double quotes like so: `"User"`  

- On ln 44 the first word should be capitalized to be consistent with other comments

- On ln 57 you need a comma between `UID` and `AID`

- I believe the tables should have comments before them to explain the use and fields. A possible example to use is from [ClassDB](https://github.com/DASSL/ClassDB/blob/dev/src/db/core/addUserMgmtCore.sql):
```sql
--Define a table to record DDL activity of users
-- no primary key is defined because there are no viable key attributes, and
-- there is no benefit to having a primary key
-- UserName is not constrained to known users because DDL activity may be
-- maintained for users who are no longer known, but see trigger definitions
-- DDLOperation and DDLObject are unsized so they can contain arbitrary strings
--Schema revisions from v2.0 to v2.1
-- New column SessionID to store session ID of the user performing each DDL op.
--Code to upgrade v2.0 schema/data to v2.1 follows the table definition
CREATE TABLE IF NOT EXISTS ClassDB.DDLActivity
(
  UserName ClassDB.IDNameDomain NOT NULL, --session user performing the operation
  StatementStartedAtUTC TIMESTAMP NOT NULL, --time at which the DDL op began
  DDLOperation VARCHAR NOT NULL --the actual DDL op, e.g., "DROP TABLE"
               CHECK(TRIM(DDLOperation) <> ''),
  DDLObject VARCHAR NOT NULL --name of the object of the DDL operation
            CHECK(TRIM(DDLObject) <> ''),
  SessionID VARCHAR(17) NOT NULL CHECK(TRIM(SessionID) <> '')
);
```
We do not have to use this style and we should discuss in our next meeting how we would like to format our comments for SQL

Another thing we need to discuss is whether we want to add Role Based Access Control, however I believe that may be addressed with a future PR.

**Comment by jgrabowski121** [comment]
Thank you @KevinKelly25 for the review. I will make the fixes that you mentioned.
- I believe the `User` table can be renamed to `ArcUser` and this will resolve the naming conflict
- I will add header comments similar to what I have done on scripts in previous project and get feedback on that style. 

Edit: changed "`User` attribute" to "`User` table"

**Comment by jgrabowski121** [comment]
In testing the file after making the updates, I realized that there is a bug in our [logical schema](https://github.com/smacademic/project-cgkm/wiki/Logical-Schema-and-Table-Summaries). 
- The table `Task` references `Arc` as a FK, but `UID` must also be referenced because the PK of the `Arc` table is (`AID`, `UID`)
- Therefore, I believe we have two options
 - We can add `UID` to the task table in the logical schema (as i have done in the create script for now so it is functional and correct) 
- Or we can have the PK of the Arc table be just AID as this should be unique and I believe we should not need a composite key

**Comment by jrm86** [comment]
I like the idea of making `AID` a `UNIQUE` attribute and avoiding the use of a composite key. It's simpler in design and I cannot think of how this could result in a insert or update conflict.
Edit: I may have been a bit redundant.  Making `AID` a PK would ensure uniqueness.

**Comment by jrm86** [comment]
Upon further review, I think we can:
- Completely remove UID from the Task table, then make TID the PK.  Tasks can only be assigned to Arcs, and arcs must have a UID.
- In the Arc table, make AID (alone) the PK.

Thoughts?

**Comment by jgrabowski121** [comment]
@jrm86 I agree that this can be done as described. However, I believe that this issue may need to wait till the next milestone because it requires changes to past documents that may cause an issue with time.
 Therefore, I recommend two options
- 1. This PR either gets put on the icebox until the changes are agreed upon and implemented in the schemas. 
- 2. We document the changes made for now as a "bandaid" and merge the changes so the file is in the repo on schedule and fix it in the upcoming milestone
Note: These changes will also cause a change to PR#17 and that should take priority because this file will not be used for our SQLite db

**Comment by jrm86** [comment]
I'd prefer option ii.  We can open a new issue to capture what needs to be updated in the documentation and affected files. @KevinKelly25, @MatthewChastain, thoughts?

**Comment by MatthewChastain** [comment]
I agree with Jon about removing UID from the task table as well as focusing on non-composite primary keys. There doesn't seem to be a need for the composite keys as part of the key in each case can become a UNIQUE attribute which maintains the structure of the DB while simultaneously simplifying our tables. 

In response to the two options @jgrabowski121, I would suggest option II, merging as is and creating an issue to be addressed by a future milestone. That issue can be set at low priority as this script focuses on the server-based implementation of the database.

**Comment by KevinKelly25** [comment]
It appears there was a mistake in the [logical schema](https://github.com/smacademic/project-cgkm/wiki/Logical-Schema-and-Table-Summaries). The logical schema should have just the AID as its primary key rather then both UID and AID. To fix this we need to change everything in arc to just have AID as primary key. This would make the issue we are having with task go away as it would just be referencing the single key. However, it is worth noting that you can reference a campsite key. An example of which is: 
```sql
FOREIGN KEY (foo_id, foo_created_on) REFERENCES foo (id, foo_created_on)
```

I think the best way to go about this is to turn the primary key for Arc to `AID` instead of the composite. I believe you guys are right and option 2 would be the best and we should correct documentation for the next milestone.

**Review by KevinKelly25 — APPROVED** [review]
It looks good now. Thank you for fixing the error.

**Review by jrm86 — APPROVED** [review]
Teamwork makes the dream work. 👍

**Review by MatthewChastain — APPROVED** [review]
Thank you for going ahead and making those changes Justin, everything looks good!

**Pull request merged**
