### PR TITLE
Feat add arc

### PR DESCRIPTION
**Pull request by jgrabowski121**
Add the ability to add an arc to the add_arc_screen
- This PR focuses modifying add_arc_screen.dart
- The data is not being validated yet

Note: The add arc screen is currently using `TextField` to accept user input. When a user selects a Parent `arc` they leave the screen and then are returned after making a selection. The TextFields are then repopulated by checking if the streams have data, and that data is displayed as hint text. This can possibly be fixed by using a `TextFormField`, or by modifying the parent arc selection screen to be a splash screen over the add arc screen instead of a different screen. Please reply with feedback on these options, and if the changes are needed before the milestone 7 release. 

Edit: Removed reference to a known issue that is no longer present

### CODE REVIEW

**Comment by KevinKelly25** [comment]
It looks good, Thank you for adding this. I just have a few comments:

- ln 179 and 183 in `bloc.dart` have an extra space. However, I believe that whole if block is unneeded and instead use the null-aware operator as such `parentArc: arcParent?.aid`. More information about null aware operators can be found [here](https://medium.com/@thinkdigitalsoftware/null-aware-operators-in-dart-53ffb8ae80bb) if you don't know them well.

- In `add_arc_screen.dart` I do not believe you need `import '../model/arc.dart';` 

- ln 86 in `add_arc_screen.dart` has extra space

- In `parent_select_screen.dart` there is some lines with adding/showing tasks to the view. I think those are unneeded as the screen will never need to show tasks. Also, it may be worth making a new `getChildren` function(s) that only retrieves arcs and not tasks

**Comment by KevinKelly25** [comment]
Another issue I just noticed is that if you go to arc view after doing add arc I can no longer see tasks. I am not sure what is causing this issue and will look into it further and reply here if I find the answer.

Also the back button does not seem to work for the parent selector screen.

**Comment by jrm86** [comment]
We can add arcs now! Thanks Justin. Checks out here, aside from Kevin's notes. I was unaware of the null-aware operator. Good find, @KevinKelly25.

**Comment by jgrabowski121** [comment]
Thank you @KevinKelly25 for the review. I did not consider using a null aware operator but I agree that using it will be the better choice over the if statements. I will also remove the unnecessary import statement and extra spaces.

 In regard to the `parent_select_screen` showing tasks as well, this was something I meant to fix prior to creating the PR but i wanted the ensure I could get feedback on the branch before I change to much, and I should have been clear on that in my description. I would prefer making changes to the parent_select_screen after we decide if it should be a splash screen or keep it as its own separate screen. However, I will begin work on creating a new `getChildren` function that will only return arcs. 

Lastly, I will work on fixing the back button asap.

**Review by jrm86 — APPROVED** [review]

**Review by MatthewChastain — APPROVED** [review]

**Review by KevinKelly25 — APPROVED** [review]
Thank you for making the changes, it looks good now @jgrabowski121

**Pull request merged**
