### PR TITLE
Add "completed" attribute to DB entities

### PR DESCRIPTION
**Pull request by jrm86**
This PR adds a Boolean attribute to arc and task entities, so that tasks and arcs may be marked as "complete". As a clarifying note, booleans are stored as `INTEGER` in SQLite, with `0` being `false` and `1` being `true`. I have defaulted these values to `false` in the class's constructors, assuming that when creating an arc or task, it is unlikely that it will already be complete. I have also updated the DB test on the Wiki (a copy of which is now in the docs folder on this branch).

### CODE REVIEW

**Review by KevinKelly25 — APPROVED** [review]
Thank you for this PR @jrm86. It looks good and the test works on my end.

**Comment by jrm86** [comment]
Forgot to add that this addresses #40

**Review by MatthewChastain — APPROVED** [review]
Looks good @jrm86, all tests pass on my end without issue. Thanks!

**Review by jgrabowski121 — APPROVED** [review]
Thanks @jrm86, everything looks good in the files changed and the tests all passed for me as well.

**Pull request merged**
