### PR TITLE
Add Home Screen and Side Menu

### LINKED ISSUE #25: Need Home Screen
ArcPlanner requires a Home screen that users will be presented with after they launch the app and after they have authenticated. 

A visual template of the UI along with details for the screen can be found [here](https://github.com/smacademic/project-cgkm/wiki/ArcPlanner-UI-Design-Template#home).

### LINKED ISSUE #27: Need Side-Menu
ArcPlanner requires a Side-Menu that users will be presented with when they swipe in from the left hand side of the screen. This will be used for navigation and help within the mobile app. This should be designed in a way that it can be easily implemented into every other screen in the app, excluding the Login screen and Loading screen.

A visual template of the UI along with details for the screen can be found [here](https://github.com/smacademic/project-cgkm/wiki/ArcPlanner-UI-Design-Template#side-menu).

### PR DESCRIPTION
**Pull request by MatthewChastain**
Added the UI build for the Home screen. At current there is no implementation of a task tile as there are no current test tasks.

Also adds in the Side Menu to the Home and About screens. This allows for navigation to completed screens in the app, currently only the Home, About, and Login screens. The Loading screen is unreachable at current as there are no operations that require significant load times.

This PR also makes slight changes to navigation in the app by moving to the Home screen after hitting the 'Login' button on the Login screen. 

closes #25, closes #27

### CODE REVIEW

**Review by KevinKelly25 — APPROVED** [review]
These changes look good. I do think some small parts may have to get changed when we convert to the BLoC pattern. However, that will be addressed in the next milestone(s) once our team fully understands that design pattern and plans accordingly.

**Comment by jrm86** [comment]
Navigation bar looks great, but I got some overflow errors on the home screen.  Tested on the Pixel emulator.  Console output reads (among other things):
```
...
I/flutter (21762): A RenderFlex overflowed by 42 pixels on the bottom.
...
I/flutter (21762): Another exception was thrown: A RenderFlex overflowed by 15 pixels on the right.
...
```

**Comment by MatthewChastain** [comment]
@jrm86 I modified the files and they should be more friendly with smaller screens. It works well on my pixel emulator now so let me know what your experience is with it!

**Review by jrm86 — APPROVED** [review]
Looks good!

**Review by jgrabowski121 — APPROVED** [review]
Thank you @MatthewChastain for adding the screen and the menu. Everything runs good in my environment and I think that the menu layout looks good. I agree with @KevinKelly25  that we may need to make changes to follow the BLoC style but for now I think the PR is ready to merge.

**Pull request merged**
