### PR TITLE
Delete arcs

### LINKED ISSUE #16: App cannot delete arcs
The app does not delete arcs.

This requirement is listed in the SRS [here](https://github.com/smacademic/project-cgkm/wiki/Software-Requirements-Specification).

### PR DESCRIPTION
**Pull request by jrm86**
Closes #16. Deletes an arc if it has no children objects. Displays a message to the user if the arc *does* have children objects.

A couple things to note:
If sending a query to SQLite that has a UUID, use quotes around the `$variable` part of the phrase. ex:
`dbClient.rawQuery('SELECT * FROM Arc WHERE ParentArc = "$uuid"');`

SQLite thinks that the UUID is a number when it is meant to be treated like a string. When it sees the dashes, it throws an exception. Adding the extra set of quotes fixes this.

I had some issues deleting an arc if it was the only arc left, but was not able to recreate the issue. I did reinstall the app on both an emulator and my Pixel handset, so the reinstall might have been the fix. Nevertheless, pay special attention to this when testing out these changes.

### CODE REVIEW

**Comment by jrm86** [comment]
Just a note - Changed the version of `table_calendar` from `^1.1.4` to `1.1.4` in pubspec.yaml. This is an unrelated, minor change that has been discussed among the team, but not yet merged into `dev`.

**Review by jgrabowski121 — APPROVED** [review]
@jrm86, thank you for adding the arc deletion functionality. In my tests, the arc is successfully deleted but i noticed that it still appears in the arc view after deletion, this however I believe to be an unrelated issue with that actual deletion of the arc. 

Note: I discovered a bug in the arc view and I will be creating an issue for it, in short if an arc only has task children, the back button will go to the previous screen and not reload the arc view as it should

**Comment by KevinKelly25** [comment]
Thank you for the change. The arc is being deleted. I am also not seeing the arc-view refresh. One other thing I noticed is that if you try to delete an arc with children at home screen it doesn't get an error message, it just does nothing.

**Comment by KevinKelly25** [comment]
Also I just noticed there are print statements in `arc_tile.dart` lines 192 and 197

**Comment by jrm86** [comment]
> ...if you try to delete an arc with children at home screen it doesn't get an error message,

I have not been able to recreate this.

Print statements have been removed. Working on the page refresh soon.

**Comment by jrm86** [comment]
I have not yet been able to find a resolution to the screen update/refresh problem. Because this PR is blocking or closely related to other PRs, I recommend we accept this PR, as is, but also create a new issue to specifically address the behavior of the UI.  Thoughts?

**Review by MatthewChastain — APPROVED** [review]
I agree with that plan @jrm86 and on that basis am approving this PR. Thanks for the work!

**Review by KevinKelly25 — APPROVED** [review]
I agree @jrm86. The PR is good to go with this new consideration

**Pull request merged**
