### PR TITLE
Display tasks on home screen

### PR DESCRIPTION
**Pull request by MatthewChastain**
This PR establishes a scroll-able list of upcoming tasks in the Home screen. At current the tasks are pulled directly from the database and the tiles are built without looking at the list of loaded Arcs and Tasks in bloc.dart. This PR mainly incorporates functions that pull Arcs and Tasks based on their due dates. The PR also adds a new helper directory, and a helper file `date.dart`.

The method of pulling Arcs and Tasks from the DB directly for this purpose is not how it should be implemented and this will be rectified in a future update. The choice of this method was mainly due to time constraints and having the date-related functions pushed for use by other team members.

### CODE REVIEW

**Comment by KevinKelly25** [comment]
The PR is working well for me. I see the following two small issues:

- ln 28 of `bloc.dart` is commented out and may be unneeded
- Was the removal of `No Due Date` on purpose for the arc_tile? If so, I am not sure that is the best choice and may require more discussion

**Comment by MatthewChastain** [comment]
Thank you @KevinKelly25 for the review. You were correct and I have now removed line 28 of `bloc.dart`. In regards to your second point I believe that it would be better to not display a "no due date" message in the absence of a due date for an Arc or Task. This would make it easier to visually scan the list for Arcs/Tasks without due dates and I feel is a cleaner implementation of the tiles. I do however want to get other opinions on this as if others feel that there should be a "no due date" message I will certainly add it back in.

**Review by jgrabowski121 — APPROVED** [review]
Everything looks good on my end, thank you @MatthewChastain

**Review by KevinKelly25 — APPROVED** [review]
Everything looks good now. Thank you for claryfying about the `No Due Dates` @MatthewChastain. As per our discussion here and in the meeting we should go with your implemented method.

**Review by jrm86 — APPROVED** [review]
Tasks on the home screen look great!  Thanks Matt.

**Pull request merged**
