### PR TITLE
Add create task screen

### LINKED ISSUE #91: Need Add Task screen
The app does not have a way to interactively add tasks. An "Add Task" screen would solve this.

### PR DESCRIPTION
**Pull request by jrm86**
Added UI and functionality for an Add Task screen.

Closes #91

### CODE REVIEW

**Comment by KevinKelly25** [comment]
Thank you @jrm86 for the PR. Adding tasks is working perfectly for me. I am seeing a very minor issue:

- Line 76, 313 and 334 of `bloc.dart` is unneeded/unused

**Comment by jrm86** [comment]
@KevinKelly25, you are correct. My last commit removed those lines.

**Comment by jgrabowski121** [comment]
This is looking really good @jrm86! The only issue I noticed is that when a `Task` is submitted the `arcParentFieldSteam` is not being initialized, so when the user goes to create another task the previous parent is still selected. I believe this can be easily fixed by adding a call to `bloc.changeArcParent(null)` in the `initializeAddTaskStreams` function in `bloc.dart`. 

Additionally, I suggest utilizing the `Observable.combineLatest2` function to ensure a Parent arc was selected since it is a required field. This can be done by replacing the parameter value `arcDescriptionFieldStream` with `arcParentFieldSteam` on line 95 of `bloc.dart`. Then, simply replace the stream used by the `submitTask()` widget in `add_task_screen.dart` with `bloc.submitValidTask`

**Comment by jrm86** [comment]
Thanks @jgrabowski121 for your suggestions. Changes made in my last commit.

**Review by KevinKelly25 — APPROVED** [review]
Everything looks good and works well for me now. Thank you for addressing those issues.

**Review by MatthewChastain — APPROVED** [review]
The only thing I notice is that the dueDate is not being displayed correctly, but I believe that other PR's have significant changes to the `task_tile.dart` file that will address this issue. Other than that small thing this looks good @jrm86 and I think it's ready to merge!

**Comment by MatthewChastain** [comment]
@jrm86 Something that I just noticed is that currently the created Task Tile does not display the Task's Location if one is given and I believe that it should above the description per the UI Design document.

**Comment by jrm86** [comment]
@MatthewChastain, Dates now show on task tiles. It did not work, at first, and I ended up finding a typo in `task.dart`.

Edit: I have also added Location to the task tile

**Review by jgrabowski121 — APPROVED** [review]
Everything looks good after the recent commits, thank you @jrm86 for the great work!

**Pull request merged**
