### PR TITLE
Create database test

### PR DESCRIPTION
**Pull request by jrm86**
This PR is for the `database_test.dart` file. A couple additions were added `databaseHelper.dart` to facilitate testing.

There are some challenges with running tests with SQFlite, as mentioned in #80 and the other issues mentioned in that thread. I've added a comment to the header to help readers be aware of this.

I'd like to draw special attention to line 30 of `database_test.dart`. I don't know why, but all tests fail if some call to the DB isn't made first. I'm interested in getting some others' point of view on getting around this.

I've also deleted the widget_test.dart file (the default one which loads with a new project).

### CODE REVIEW

**Review by MatthewChastain — APPROVED** [review]
I ran the tests after deleting the application on my physical device and all tests passed. I had ran it initially with the application still installed and many tests failed due to the existence of the database already in the system. 

In regards to your line 30, I am unsure of why it is needed unless a connection is somehow not established up until the first call, opening it for future calls.

**Comment by jrm86** [comment]
@MatthewChastain, that may have been due to the addition of the `startTransaction()` and `rollback()` functions to the dbhelper class (which would need a new install). Were you able to recreate the failure? I'm going to run a couple more tests.

**Comment by jrm86** [comment]
I believe I found the source of the issue @MatthewChastain mentioned. The `insert()` method of the SQFlite plugin, which is used in our `insertUser()` and `insertArc()` functions, will return the total number of rows in the applicable table on completion of the query. I had assumed it would return the total number of *affected* rows in the applicable table, which would be 1. My mistake was testing an empty database, which would yield passing results from an incorrect test. Regardless, to get the correct number, I needed to query the database, so this means we can give purpose to the `await db.getUserCount();` which was on line 30. That line has been edited/added to the `Add user test`

**Review by KevinKelly25 — APPROVED** [review]
The tests run well for me. Thank you for the very good start to the much needed testing of our application @jrm86 

I am unsure what was causing the issue at first with line 30 but it has a purpose now. However, we should keep this in mind if we have problem in the future with this.

**Comment by jrm86** [comment]
> I am unsure what was causing the issue at first with line 30 but it has a purpose now. However, we should keep this in mind if we have problem in the future with this.

Agreed.

**Review by jgrabowski121 — APPROVED** [review]
Thank you @jrm86 for adding these tests, everything passed in my environment as well.

**Pull request merged**
