### PR TITLE
Add Screen UI Coding Specifications

### LINKED ISSUE #30: Need Screen UI Coding Specifications
In order to ensure that all built screens are programmed in such a way as to guarantee conformity regardless of the developer, I propose that we create a wiki document that details Dart coding specifications. This includes such items as text sizes, panel spacing, width and height restrictions, color schemes, button layout, and other similar items and concepts.

### PR DESCRIPTION
**Pull request by MatthewChastain**
Added the ArcPlanner Screen Coding Specifications document to the branch. The purpose of the document is to start conversation about the app's UI style and is open to discussion and changes. This should the place to come to see how certain aspects of screens are built in ArcPlanner. If you come across an aspect of screen design that isn't touched upon in this document, feel free to make a section for it and start a conversation about it. The document as is should give some structure as to how we shape certain screen widgets.

closes #30

### CODE REVIEW

**Comment by MatthewChastain** [comment]
@jgrabowski121 I believe that the settings screen should be based off the `ListTile` widget instead of the `FlatButton` widget. It should make the screen much easier to expand if future settings need to be added.

Regardless of the decision we make on this, it should be added to the document which I will take care of when we reach a consensus.

**Review by KevinKelly25 — APPROVED** [review]
Thank you @MatthewChastain for writing this. It helped me understand the front end of what we are doing a little more then I did.

**Comment by jgrabowski121** [comment]
@MatthewChastain I agree with your suggestion and I have mentioned the fix for issue #48 in the comments for that PR.

**Comment by jrm86** [comment]
Coding Specs look great.  I'll be testing the about screen shortly.

**Review by jrm86 — APPROVED** [review]
Thanks Matt.  Everything checks out!

**Review by jgrabowski121 — APPROVED** [review]

**Pull request merged**
