### PR TITLE
Create classes for ArcUser, Ark, and Task

### PR DESCRIPTION
**Pull request by jgrabowski121**
Add the classes for `ArkUser`, `Ark`, and `Task` as well as the insert, update and delete functions
These classes are in separate files in the model folder
The insert, delete, and update operations are in `databaseHelper.dart`
This PR closes issue #22

### CODE REVIEW

**Comment by KevinKelly25** [comment]
Thank you for the PR @jgrabowski121 and @jrm86. I do believe this also closes issue #18.

I am getting better with dart but still learning. These are more questions then comments but may help me and maybe others understand more.

1) How come the classes have getters but not setters?
2) What are the benefits to passing whole object to insert and update operations vs just the UUID?

**Comment by jrm86** [comment]
@KevinKelly25, to answer your questions: 1. I made an assumption that getters would be more useful to pull individual elements from an object to be used in various widgets, etc.  2 (and kinda 1). The idea is that the app would interact with objects from classes, and then just pass the object to the DB client to do the rest.  Once we start implementing other parts of the app, we can change them as needed.

**Comment by KevinKelly25** [comment]
Thank you for the explanation @jrm86.

Most of it looks fine. There is just one small issue that was reintroduced. In `databaseHelper.dart` the UUIDs went from `==` to `<=` .

**Comment by jrm86** [comment]
I had to make a few adjustments to enable some kind of testing, which can be seen in my last few commits.
- Constructors for Arcs and Tasks include uid and aid, respectively.
- Constraints for UUID have been changed to <= to account that we do not yet have UUID working yet

I'd like to address support for UUID separately. I will open an issue for it shortly. The UUIDs I've been able to produce are not 60 chars in length, but I don't want this one issue to delay other work that might be relying on the classes in this PR.

I've written a very simple [test ](https://github.com/smacademic/project-cgkm/wiki/Basic-DB-test)that can be used to verify the DB.  Its output can be read in the debug console.

Edit: If you've already run the program on a device (physical or virtual), you may have to uninstall it for the changes to take affect.

**Review by KevinKelly25 — APPROVED** [review]
Ahh, makes sense. I think leaving it at `<=` for now and opening an issue as you said would be the best way to do it. It looks good to merge now

**Comment by MatthewChastain** [comment]
Upon reviewing I notice that you have left areas to implement a Widget build in the `arc.dart`, `task.dart`, and `user.dart` files. These shouldn't be files that we build the screens in, rather just the classes that we'll import into the build files for use. 

I also notice that in some areas to access the class variables you use `this._variable` and in other areas you use just `_variable`. While both work without issue, I recommend that we stick with one or the other. I personally like just using the variable name without `this.` in front but this is a decision the group should make together. 

The `databaseHelper.dart` file is coming along nicely, I like the change to using the private member variables with the underscore syntax.

**Comment by KevinKelly25** [comment]
I agree that we should stick to either `this.variable` or `_variable`. I prefer the use of `this` for member variables as it is understandable by anyone that understands this while also eliminating many. I do believe `_variable` may accomplish the same goal as long as we make it very obvious how we are using the `_`.

**Comment by jrm86** [comment]
Upon review of the Dart language [site](https://www.dartlang.org/guides/language/language-tour#constructors), I did see that the baseline constructor, at least, use the `this` qualifier. After a quick test with and without the `this` qualifier, this seems to be the case. It seems to run fine without the use of `this` in the other constructors (`toMap` and `fromMap`). I'll wait to push any commits until we have an agreement.

Also @KevinKelly25 , the use of the underscore makes things private (whether they're variables, functions, etc). Dart doesn't have `public` or `private` keywords. It's not a naming style; it actually affects the behavior of the program.  More info [here](https://www.dartlang.org/guides/language/language-tour#important-concepts).

**Comment by KevinKelly25** [comment]
Ahh, I didn't realize that. Thank you for clarifying @jrm86. I am fine with either implementation then.

**Review by jrm86 — APPROVED** [review]

**Review by MatthewChastain — APPROVED** [review]
I think this looks good! Thanks for the work guys!

**Pull request merged**
