### PR TITLE
Add subarc view

### LINKED ISSUE #57: Moving to Sub-Arcs in Arc view is not possible
Currently users are unable to move from Arc view with "master Arcs" into subArcs. I believe this issue is being caused one of three things:
- The stream is sending incorrect data from the children
- The child tiles are being generated incorrectly
- Wrong data/missing data is being sent upon click of Arc

### PR DESCRIPTION
**Pull request by KevinKelly25**
This PR adds the ability to move from the "MasterArc" list to a subArc. To do this I had to do the following:

- Add a map function `transformData` to the stream that transforms the data in the stream to the "proper" data object. The "proper" object is determined by a flag that is added into the `stream.sink`
- Modify functions to fit into the above object/flag structure
- Change `getChildren` function to correctly obtain children of given arc from database
- Fix error in `databaseHelper.dart` that was referencing wrong column and wasn't using quotes around string values

closes #57

### CODE REVIEW

**Review by MatthewChastain — APPROVED** [review]
Diving into a second layer of Arcs works perfectly! Really nice to see this functionality implemented. Thank you @KevinKelly25!

**Review by jgrabowski121 — APPROVED** [review]
Everything worked out well in the test, thank you @KevinKelly25 for adding the subarc functionality

**Review by jrm86 — APPROVED** [review]
Excellent!  Thanks @KevinKelly25

**Comment by KevinKelly25** [comment]
Thank you for the reviews 👍

**Pull request merged**
