### PR TITLE
Add time due field

### PR DESCRIPTION
**Pull request by jgrabowski121**
This PR has made numerous changes to add the time field to the application

Changes include: 
- Add 'time due' field to the add arc and add task screen
- Add 'time due' field to the arc and task tiles
- Add 'time due' field to the task view screen: Note; if a `Task` has no time due it will display that its due at "11:59 PM" on this screen which is hard coded

### CODE REVIEW

**Comment by KevinKelly25** [comment]
The addition of time was very nice. It is almost ready to merge except for two small issues:

1) There is commented out code in `add_arc_screen.dart` that needs to be removed
2) `completeArc` in `bloc.dart` needs to be commented

**Comment by jgrabowski121** [comment]
@KevinKelly25  thank you for the feedback. I will add the comment as mentioned, but with regard to the commented out code I meant to comment on that in my PR message: The commented out code contains alternatives to the implemented date picker that I am in the processes of implementing but that is not yet complete, and I planned to keep it it the file, however I can add a comment line stating why it is present. *I will however remove the unneeded import that is commented out*

**Review by KevinKelly25 — APPROVED** [review]
Ahh, that is okay. I didn't realize. I will approve then. Thank you

**Review by MatthewChastain — APPROVED** [review]
Looks good @jgrabowski121. Thank you for adding this functionality. We should make an issue that it is not yet implemented with other screens.

**Review by jrm86 — APPROVED** [review]

**Pull request merged**
