### PR TITLE
Fix null date issue with task and arc creation

### PR DESCRIPTION
**Pull request by KevinKelly25**
This PR fixes null date issue with task and arc creation.

### CODE REVIEW

**Comment by MatthewChastain** [comment]
I can now add a Task or Arc without inserting a due date, but cannot see the created arc or task in the arc view after creation.

**Review by jrm86 — APPROVED** [review]
Thanks for this fix Kevin

**Comment by MatthewChastain** [comment]
> 
> 
> I can now add a Task or Arc without inserting a due date, but cannot see the created arc or task in the arc view after creation.

Just took a restart of the DB to get it working. Everything seems to work fine. Thanks @KevinKelly25!

**Review by MatthewChastain — APPROVED** [review]

**Review by jgrabowski121 — APPROVED** [review]
Thanks for the fix

**Pull request merged**
